"""add payment cards

Revision ID: 29980c3536e8
Revises: e2dadb16a936
Create Date: 2026-08-05 12:29:22.373339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29980c3536e8'
down_revision: Union[str, Sequence[str], None] = 'e2dadb16a936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('card_holder', sa.String(length=255), nullable=False),
    sa.Column('min_amount', sa.BigInteger(), nullable=False),
    sa.Column('max_amount', sa.BigInteger(), nullable=False),
    sa.Column('payment_note', sa.String(length=255), nullable=True),
    sa.Column('qr_image', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_cards_card_number'), 'payment_cards', ['card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_cards_card_number'), table_name='payment_cards')
    op.drop_table('payment_cards')
    # ### end Alembic commands ###
