"""add service api name

Revision ID: 720e8fbdc77b
Revises: f9b739920047
Create Date: 2026-08-09 08:47:37.378250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e8fbdc77b'
down_revision: Union[str, Sequence[str], None] = 'f9b739920047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('api_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'api_name')
    # ### end Alembic commands ###
